configmap:
  dupeguru:
    data:
      DISPLAY_HEIGHT: "{{ .Values.dupeguru.DISPLAY_HEIGHT }}"
      DISPLAY_WIDTH: "{{ .Values.dupeguru.DISPLAY_WIDTH }}"
      ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.dupeguru.ENABLE_CJK_FONT }}'
      KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.dupeguru.KEEP_APP_RUNNING }}'
      SECURE_CONNECTION: '{{ ternary "1" "0" .Values.dupeguru.SECURE_CONNECTION }}'
    enabled: true
dupeguru:
  DISPLAY_HEIGHT: 768
  DISPLAY_WIDTH: 1280
  ENABLE_CJK_FONT: false
  KEEP_APP_RUNNING: false
  SECURE_CONNECTION: false
image:
  pullPolicy: IfNotPresent
  repository: jlesage/dupeguru
  tag: v24.01.1@sha256:2a2e907f545ce90538be5133b4ce23ba8e3add3bc6f6aa2a00dbd552c256817b
persistence:
  config:
    enabled: true
    mountPath: /config
  storage:
    enabled: true
    mountPath: /storage
  trash:
    enabled: true
    mountPath: /trash
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10260
        targetPort: 5800
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 10261
        targetPort: 5900
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PASSWORD: ""
          envFrom:
            - configMapRef:
                name: "dupeguru"
