image:
  pullPolicy: IfNotPresent
  repository: minims/somfyprotect2mqtt
  tag: 2024.1.0@sha256:c31838539a55c9420927c69eeb693059d358cd852e9dd673c4f31c6a4149b6d9
persistence:
  configfile:
    defaultMode: "0600"
    enabled: true
    mountPath: /config/config.yaml
    objectName: somfyprotect2mqtt-secret
    readOnly: true
    subPath: config.yaml
    type: secret
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
somfyprotect2mqtt:
  delay_device: 60
  delay_site: 10
  ha:
    alarm_code: 1234
    alarm_code_arm_required: false
    alarm_code_disarm_required: true
  manual_snapshot: false
  mqtt:
    client_id: client_id
    ha_discover_prefix: homeassistant
    host: 0.0.0.0
    password: password
    port: 1883
    topic_prefix: somfyProtect2mqtt
    username: admin
  somfy:
    password: password
    sites:
      - Maison
    username: admin
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
