image:
  pullPolicy: IfNotPresent
  repository: leantime/leantime
  tag: 3.0.3@sha256:f879cba9c7532780a37a212944617c29e0e8c22eac0790b0c0d6ddedb0f52f2c
mariadb:
  enabled: true
  existingSecret: mariadbcreds
  mariadbDatabase: leantime
  mariadbUsername: leantime
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10117
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LEAN_APP_URL:
              "{{ if .Values.ingress }}{{ if .Values.ingress.main.enabled
              }}https://{{ ( index .Values.ingress.main.hosts 0 ).host }}{{ end }}{{
              end }}"
            LEAN_DB_DATABASE: "{{ .Values.mariadb.mariadbDatabase }}"
            LEAN_DB_HOST:
              secretKeyRef:
                key: plainhost
                name: mariadbcreds
            LEAN_DB_PASSWORD:
              secretKeyRef:
                key: mariadb-password
                name: mariadbcreds
            LEAN_DB_USER: "{{ .Values.mariadb.mariadbUsername }}"
            LEAN_SESSION_PASSWORD:
              secretKeyRef:
                key: LEAN_SESSION_PASSWORD
                name: leantime-secrets
